### PR TITLE
New signature for passing injections

### PR DESCRIPTION
**Pull request by eldadfux**
Attempt to make the route signature more verbose.

Before:

```php
App::get('/hello-world') // Define Route
    ->action(
        function($request, $response) {
            $response
              ->addHeader('Cache-Control', 'no-cache, no-store, must-revalidate')
              ->addHeader('Expires', '0')
              ->addHeader('Pragma', 'no-cache')
              ->json(['Hello' => 'World']);
        }, ['request', 'response']);
```

After:

```php
App::get('/hello-world') // Define Route
    ->inject('request')
    ->inject('response')
    ->action(
        function($request, $response) {
            $response
              ->addHeader('Cache-Control', 'no-cache, no-store, must-revalidate')
              ->addHeader('Expires', '0')
              ->addHeader('Pragma', 'no-cache')
              ->json(['Hello' => 'World']);
        });
```

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
I think you missed 2 cache files :+1:

**Comment by eldadfux** [comment]
Updated the code example above to make more sense.

**Comment by eldadfux** [comment]
Added the option to mix between params and injection to allow maximum flexibility. Injection and params can be set in any order you wish at the start, or at the end, you even mix them together (😒)

**Comment by christyjacob4** [comment]
Looks good eldad. 👍

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
