### PR TITLE
Allow consuming the entire request body as an un-keyed parameter

### PR DESCRIPTION
**Pull request by abnegate**

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey, Jake, not sure what is the use case, but it would make more sense to you the request object to get the entire request payload instead of having as a framework specific feature. Let me know if I missed anything.

**Comment by abnegate** [comment]
@eldadfux The use case is for GraphQL query batching, where the endpoint should accept a raw array of queries.

The issue with that approach is that with no route parameter, the GraphQL service methods would not be able to send a request body on the SDK side. But that _is_ outside the scope of framework features. 

Looking for another approach, we could use 2 route labels instead, one for marking the route as using the full request body and one for the parameter name to use in SDKs, then process these in the spec generator. What do you think?

**Comment by eldadfux** [comment]
Do you have any code examples that show how this was planned to use inside the GraphQL server?

**Comment by abnegate** [comment]
@eldadfux The GraphQL routes (GET/POST on the same endpoint) would both have a single `fullBody` parameter:

```
    ->param('query', '', new JSON(), 'The query or queries to execute.', fullBody: true)
```

Which would allow them to accept the following bodies:

```
{
    "query": "",
    "operationName": "",
    "variables": {}
}
```
```
[
  {
      "query": "",
      "operationName": "",
      "variables": {}
  }
]
```

and SDK's could have:

```
Graphql.query(query: [])
Graphql.mutate(query: [])
```

**Pull request closed without merging**
