### PR TITLE
Feat: Hostname validator

### PR DESCRIPTION
**Pull request by Meldiron**
Added a hostname validator that can be used instead of our current `Text` validator for hostnames. Key features:

- Validates that port, protocol and route is not part of the hostname
- Supports wildcard whitelists. `matej.app.com` is a valid hostname for pattern `*.app.com`

This PR will be useful for Appwrite for:

- Adding new platform
- Preparing CORS for request

This will let Appwrite validate if a platform was added properly, and add wildcard support.

Tests added ✅

### CODE REVIEW

**Comment by kodumbeats** [comment]
Are we deprecating the Host validator in Appwrite?
https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Network/Validator/Host.php

**Review by eldadfux — COMMENTED** [review]
What happens when we only submit `*`?

**Comment by Meldiron** [comment]
> Are we deprecating the Host validator in Appwrite? https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Network/Validator/Host.php

Yes, looks like we are. We had that before? 🤔 I noticed hostname validation in different places in Appwrite and they didn't use this validator. Good thing we are migrating into one place.

**Comment by Meldiron** [comment]
> What happens when we only submit `*`?

It fails with `Wildcard at the end of hostname '*' is not allowed.` for the same reason why we don't allow `mydomain.*`. I would also say this is intended for security reasons.

I added test for `*`.

I was thinking about updating validator to make sure there is at least one dot `.` in the hostname, but that would not make sense since `localhost` should be valid hostname (added that to tests too).

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
